name: Update ODUG Website
on: [push]
jobs:
  rebuild-website:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh website files from repository
        uses: actions/checkout@v4
      - name: Get theme submodule
        uses: actions/checkout@v4
        with:
          repository: corneliusdavid/hugo-pascalinia
          path: themes/pascalinia
          
      - name: Build website with Hugo
        uses: jakejarvis/hugo-build-action@master
        with:
            args: --minify --buildFuture

      - name: Push to the Web
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
