name: Update ODUG Website
on: [push]
jobs:
  rebuild-website:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh website files from repository
        env:
          TZ: 'America/Los_Angeles'
        uses: actions/checkout@v4
          
      - name: Get theme submodule
        env:
          TZ: 'America/Los_Angeles'
        uses: actions/checkout@v4
        with:
          repository: corneliusdavid/hugo-pascalinia
          path: themes/pascalinia
          
      - name: Build website with Hugo
        env:
          TZ: 'America/Los_Angeles'
        uses: jakejarvis/hugo-build-action@master
        with:
          args: --minify --buildFuture  
            
      - name: Push to the Web
        env:
          TZ: 'America/Los_Angeles'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: public/
          state-name: ../.ftp-deploy-sync-state.json
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
