name: Update ODUG Website
on: [push]
jobs:
  rebuild-website:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh website files from repository
        uses: actions/checkout@v2
          
      - name: Build website with Hugo
        uses: jakejarvis/hugo-build-action@v0.111.3
        with:
            args: --minify --buildFuture

      - name: Push to the web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          ftp_server: ${{ secrets.FTP_SERVER }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
