name: Update ODUG Website
on: [push]
jobs:
  rebuild-website:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh website files from repository
        run: git pull origin master --recurse-submodules
        shell: bash
          
      - name: Build HTML files for publishing
        run: hugo --minify --buildFuture --verbose
        shell: bash

      - name: Push to the web
        run: upload.sh ${{ secrets.ODUG_SITE_HOST }} ${{ secrets.ODUG_SITE_USER }} ${{ secrets.ODUG_SITE_PASS }} ${{ vars.LOCAL_SRC }}  ${{ vars.DEST_FOLDER }}
        shell: bash  
